# Generated by Django 5.2 on 2025-04-16 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('LO', 'On Loan'), ('RE', 'Reserved'), ('MA', 'Maintenance'), ('LO', 'Lost'), ('DA', 'Damaged'), ('WD', 'Withdrawn')], default='AV', max_length=2)),
                ('shelf_location', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='library.book')),
            ],
            options={
                'verbose_name_plural': 'Book copies',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('OV', 'Overdue'), ('RE', 'Returned'), ('LO', 'Lost'), ('DA', 'Damaged')], default='AC', max_length=2)),
                ('renewed_count', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='circulation.bookcopy')),
            ],
            options={
                'ordering': ['-checkout_date'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('LA', 'Late Return'), ('DA', 'Damage'), ('LO', 'Lost Item'), ('PR', 'Processing'), ('OT', 'Other')], default='LA', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_assessed', models.DateField(default=django.utils.timezone.now)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OU', 'Outstanding'), ('PA', 'Paid'), ('WA', 'Waived')], default='OU', max_length=2)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='circulation.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('membership_date', models.DateField(default=django.utils.timezone.now)),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('STD', 'Standard'), ('PRE', 'Premium'), ('STU', 'Student'), ('SEN', 'Senior')], default='STD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='circulation.member'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('AC', 'Active'), ('FU', 'Fulfilled'), ('CA', 'Cancelled'), ('EX', 'Expired')], default='AC', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='library.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='circulation.member')),
            ],
            options={
                'ordering': ['reservation_date'],
            },
        ),
    ]
